python3.7 ../train.py \
--lambda1 1. \
--lambda2 0.5 \
--device "cuda:4" \
--loss3_type "triplet" \
--triplet_margin 2. \
--txt_result_prefix "../logs/txt/3.17/config4" \
--tb_result_dir "../logs/tb/3.17/config4" \
--model_prefix "../models/3.17/config4/VAE" \
--optimizer_prefix "../models/3.17/config4/VAE_opt" \
--batch_size 16 \
--validation_batch_size 16